spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=autosalon
    username: postgres
    password: 123456

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
    schemas: autosalon
    init-sql: CREATE SCHEMA IF NOT EXISTS autosalon;
    create-schemas: true

  jpa:
    properties:
      hibernate.default_schema: autosalon
      hibernate.hbm2ddl.create_namespaces: true
    hibernate:
      ddl-auto: none
  #server:
  #port: 8080